version: "3.3"
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: apache-php
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: mysql8
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/data
volumes:
  mysql_data:
